version: "3.9"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: informatica
      MYSQL_USER: informatica
      MYSQL_PASSWORD: informatica
  
  backend:
    build: 
      context: ./backproyectoinformatica
      dockerfile: Dockerfile     

volumes:
  db_data: