version: "3.9"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: informatica
      MYSQL_USER: informatica
      MYSQL_PASSWORD: informatica
  
  backend:
    build: 
      context: ./backproyectoinformatica
      dockerfile: Dockerfile    
    depends_on:
      - mysql 
    ports:
      - "5000:5000"

  front:
    build:
      context: ./YouCook/YouCookFront
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8000:80"

volumes:
  db_data: